---
title: "Untitled"
author: "Dianah Marie Canonicato"
date: "2024-02-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

install.packages("dplyr")
install.packages("rvest")
install.packages("httr")
install.packages("polite")

SCRAPING FOR 50

Movie 1
```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

movie1 <- data.frame()

for (page in 1:5) {
  link1 <- paste0("https://www.imdb.com/title/tt0903747/reviews?ref_=tt_urv", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  MovieName1 <- "Breaking Bad (2008–2013)"
  scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes("div.display-name-date:nth-of-type(2) a")[1:10]
  scrapedReview <- scrapeNodes("div.collapsable:nth-of-type(n+2) div.text, div:nth-of-type(n+15) span.spoiler-warning")[1:10]
  scrapedDate <- scrapeNodes("div.display-name-date:nth-of-type(2) span.review-date")[1:10]
  scrapedRating <- scrapeNodes("div.ipl-ratings-bar")[1:10]
  scrapedType <- scrapeNodes(".sc-ab73d3b3-1 a.ipc-metadata-list-item__list-content-item")[1:10]

movie1 <- rbind(movie1, data.frame(
    movie_name = MovieName1,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_movie= scrapedType
  ))

  
}

View(movie1)

```


Movie 2
```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

movie2 <- data.frame()

for (page in 1:5) {
  link2 <- paste0("https://www.imdb.com/title/tt5491994/reviews?ref_=tt_urv", page)
  session2 <- bow(link2, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session2) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  movieName2 <- "Planet Earth II (2016)"
  scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".collapsable div:nth-of-type(2) .display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("div.content:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable span.rating-other-user-rating")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  movie2 <- rbind(movie2, data.frame(
    movie_name = movieName2,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_movie = scrapedType
  ))


}

View(movie2)

```


movie3
```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

movie3 <- data.frame()

for (page in 1:5) {
  link3 <- paste0("https://www.imdb.com/title/tt0417299/reviews?ref_=tt_urv", page)
  session3 <- bow(link3, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session3) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  movieName <- "Avatar: The Last Airbender (2005–2008)"
  scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("div.lister-item:nth-of-type(n+3) div:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable span.rating-other-user-rating")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  movie3 <- rbind(movie3, data.frame(
    prod_name = movieName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))


}

View(movie3)

```


Movie 4
```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

movie4 <- data.frame()

for (page in 1:5) {
  link4 <- paste0("https://www.imdb.com/title/tt0111161/reviews?ref_=tt_urv", page)
  session4 <- bow(link4, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session4) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  movieName <- "The Shawshank Redemption (1994)"
  scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("span.spoiler-warning, div.content:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable div.ipl-ratings-bar")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  movie4 <- rbind(movie4, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

View(movie4)

```



Movie 5
```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

movie5 <- data.frame()

for (page in 1:5) {
  link5 <- paste0("https://www.imdb.com/title/tt0120737/reviews?ref_=tt_urv", page)
  session5 <- bow(link5, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session5) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  movieName <- "The Lord of the Rings: The Fellowship of the Ring"
  scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("span.spoiler-warning, div.content:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable div.ipl-ratings-bar")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  movie5 <- rbind(movie5, data.frame(
    movie_name = movieName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  
}

View(movie5)

```


Movie 6
```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

movie6 <- data.frame()

for (page in 3:7) {
  link6 <- paste0("https://www.imdb.com/title/tt0468569/reviews?ref_=tt_urv", page)
  session6 <- bow(link6, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session6) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  
  movieName <- "The Dark Knight (2008)"
  scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("span.spoiler-warning, div.content:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable div.ipl-ratings-bar")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  movie6 <- rbind(movie6, data.frame(
    movie_name = movieName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
    
  ))

 

  
}

View(movie6)

```

Movie7
```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Movie7 <- data.frame()

for (page in 3:7) {
  link7 <- paste0("https://www.imdb.com/title/tt0118799/reviews?ref_=tt_urv", page)
  session7 <- bow(link7, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session7) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("span.spoiler-warning, div.content:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable div.ipl-ratings-bar")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  Movie7 <- rbind(Movie7, data.frame(
    movie_name = movieName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
))

}

View(Movie7)

```


Movie 8
```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

movie8 <- data.frame()

for (page in 3:7) {
  link8 <- paste0("https://www.imdb.com/title/tt0047478/reviews?ref_=tt_urv", page)
  session8 <- bow(link8, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session8) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  movieName <- "Seven Samurai (1954)"
  scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("span.spoiler-warning, div.content:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable div.ipl-ratings-bar")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

 movie8 <- rbind(movie8, data.frame(
    movie_name = movieName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  
}

View(movie8)
```

Movie9
```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Movie9 <- data.frame()

for (page in 3:7) {
  link9 <- paste0("https://www.imdb.com/title/tt0317248/reviews?ref_=tt_urv", page)
  session9 <- bow(link9, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session9) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  movieName <- "City of God (2002)"
   scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("span.spoiler-warning, div.content:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable div.ipl-ratings-bar")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

 Movie9 <- rbind(Movie9, data.frame(
    movie_name = movieName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  
}

View(Movie9)
```

Movie10
```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

movie10 <- data.frame()

for (page in 6:10) {
  link10 <- paste0("https://www.imdb.com/title/tt0102926/reviews?ref_=tt_urv", page)
  session10 <- bow(link10, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session10) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

 movieName <- "The Silence of the Lambs (1991)"
   scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("span.spoiler-warning, div.content:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable div.ipl-ratings-bar")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

 movie10 <- rbind(movie10, data.frame(
    movie_name = movieName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  
}

View(movie10)
```

Movie11
```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

movie11 <- data.frame()

for (page in 3:7) {
  link11 <- paste0("https://www.imdb.com/title/tt0245429/reviews?ref_=tt_urv", page)
  session11 <- bow(link11, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session11) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
  movieName <- "Spirited Away (2001))"
  scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("span.spoiler-warning, div.content:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable div.ipl-ratings-bar")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]


movie11 <- rbind(movie11, data.frame(
    movie_name = movieName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))


}

View(movie11)
```

Movie12
```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

movie12 <- data.frame()

for (page in 3:7) {
  link12 <- paste0("https://www.imdb.com/title/tt6751668/reviews?ref_=tt_urv", page)
  session12 <- bow(link12, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session12) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

 movieName <- "Spirited Away (2001))"
  scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("span.spoiler-warning, div.content:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable div.ipl-ratings-bar")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]


movie12 <- rbind(movie12, data.frame(
    movie_name = movieName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

View(movie12)
```
Movie13
```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

movie13 <- data.frame()

for (page in 3:7) {
  link13 <- paste0("https://www.imdb.com/title/tt2380307/reviews?ref_=tt_urv", page)
  session13 <- bow(link12, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session13) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

 movieName <- "Coco (I) (2017))"
  scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("span.spoiler-warning, div.content:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable div.ipl-ratings-bar")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]


movie13 <- rbind(movie13, data.frame(
    movie_name = movieName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

}

View(movie13)
```

Movie14
```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

movie14 <- data.frame()

for (page in 3:7) {
  link14 <- paste0("https://www.imdb.com/title/tt2380307/reviews?ref_=tt_urv", page)
  session14 <- bow(link14, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session14) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

 movieName <- "Psycho (1960))"
  scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("span.spoiler-warning, div.content:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable div.ipl-ratings-bar")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]


movie14 <- rbind(movie14, data.frame(
    movie_name = movieName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

}

View(movie14)

```

Movie15
```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

movie15 <- data.frame()

for (page in 3:7) {
  link15 <- paste0("https://www.imdb.com/title/tt2380307/reviews?ref_=tt_urv", page)
  session15 <- bow(link15, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session15) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

 movieName <- "The Usual Suspects (1995))"
  scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("span.spoiler-warning, div.content:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable div.ipl-ratings-bar")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]


movie15 <- rbind(movie15, data.frame(
    movie_name = movieName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

}

View(movie15)

```

Movie16
```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

movie16 <- data.frame()

for (page in 3:7) {
  link16 <- paste0("https://www.imdb.com/title/tt2380307/reviews?ref_=tt_urv", page)
  session16 <- bow(link16, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session16) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

 movieName <- "The Usual Suspects (1995))"
  scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("span.spoiler-warning, div.content:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable div.ipl-ratings-bar")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]


movie16 <- rbind(movie16, data.frame(
    movie_name = movieName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

}

View(movie16)


```

Movie17
```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

movie17 <- data.frame()

for (page in 3:7) {
  link17 <- paste0("https://www.imdb.com/title/tt2380307/reviews?ref_=tt_urv", page)
  session17 <- bow(link17, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session17) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

 movieName <- "Harakiri (1962))"
  scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("span.spoiler-warning, div.content:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable div.ipl-ratings-bar")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]


movie17 <- rbind(movie17, data.frame(
    movie_name = movieName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

}

View(movie17)


```

Movie18
```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

movie18 <- data.frame()

for (page in 3:7) {
  link17 <- paste0("https://www.imdb.com/title/tt26047818/reviews?ref_=tt_urv", page)
  session18 <- bow(link18, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session18) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

 movieName <- "Anyone But You (2023))"
  scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("span.spoiler-warning, div.content:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable div.ipl-ratings-bar")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]


movie18 <- rbind(movie18, data.frame(
    movie_name = movieName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

}

View(movie18)


```

Movie19
```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Movie19 <- data.frame()

for (page in 3:7) {
  link19 <- paste0("https://www.imdb.com/title/tt2380307/reviews?ref_=tt_urv", page)
  session19 <- bow(link19, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session19) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

 movieName <- "American Beauty (1999))"
  scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("span.spoiler-warning, div.content:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable div.ipl-ratings-bar")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]


Movie19 <- rbind(Movie19, data.frame(
    movie_name = movieName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

}

View(Movie19)

```
Movie20

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Movie20 <- data.frame()

for (page in 3:7) {
  link20 <- paste0("https://www.imdb.com/title/tt0133093/reviews?ref_=tt_urv", page)
  session20 <- bow(link20, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session20) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

 movieName <- "The Matrix (1999))"
  scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("span.spoiler-warning, div.content:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable div.ipl-ratings-bar")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]


Movie20 <- rbind(Movie20, data.frame(
    movie_name = movieName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

}

View(Movie20)
```

Movie21

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Movie21  <- data.frame()

for (page in 3:7) {
  link21 <- paste0("https://www.imdb.com/title/tt11762114/reviews?ref_=tt_urv", page)
  session21 <- bow(link21, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session21) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

 movieName <- "Mean Girls (2024))"
  scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("span.spoiler-warning, div.content:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable div.ipl-ratings-bar")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]


Movie21 <- rbind(Movie21, data.frame(
    movie_name = movieName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

}

View(Movie21)
```

Movie22
```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

Movie22  <- data.frame()

for (page in 3:7) {
  link22 <- paste0("https://www.imdb.com/title/tt0110912/reviews?ref_=tt_urv", page)
  session22 <- bow(link22, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session22) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

 movieName <- "Pulp Fiction (1994))"
  scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("span.spoiler-warning, div.content:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable div.ipl-ratings-bar")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]


Movie22 <- rbind(Movie22, data.frame(
    movie_name = movieName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

}

View(Movie22)

```

movie23
```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

movie23  <- data.frame()

for (page in 3:7) {
  link23 <- paste0("https://www.imdb.com/title/tt6751668/reviews?ref_=tt_urv", page)
  session23 <- bow(link23, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session23) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

 movieName <- "Parasite (2019))"
  scrapedTitle <- scrapeNodes("a.title")[1:10]
  scrapedReviewer <- scrapeNodes(".display-name-link a")[1:10]
  scrapedReview <- scrapeNodes("span.spoiler-warning, div.content:nth-of-type(3) div.text")[1:10]
  scrapedDate <- scrapeNodes("span.review-date")[1:10]
  scrapedRating <- scrapeNodes(".collapsable div.ipl-ratings-bar")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]


movie23 <- rbind(movie23, data.frame(
    movie_name = movieName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

}

View(movie23)

```
